name: movie_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  vertical_tabs: ^0.2.0
  # 网络请求
  dio: ^3.0.9
  video_player: ^0.10.11+1
  #chewie:  ^0.10.0
  # 图片加载
  cached_network_image: 2.0.0-rc
  quantize_dart: ^1.0.3
  # 工具类
  flustars: 0.2.6+1
  device_info: 0.4.0+2
  # 视频播放
  flutter_ijkplayer: 0.3.5+1

  # 下拉刷新、上拉加载
  flutter_easyrefresh: ^2.0.4
  pull_to_refresh: ^1.5.7
  shimmer: 1.0.0
  # 状态管理
  provider: ^4.3.2+2
  # 吐司
  oktoast: ^2.1.7

  # 路由管理
  fluro: ^1.7.7

  # 日志打印
  logger: ^0.7.0+2
  # 轮播图
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.0.2
  fluttertoast: ^4.0.1
  image_picker: ^0.6.7+1
  image_cropper: ^1.2.2
  screen: ^0.0.5
  transparent_image: ^1.0.0
  auto_orientation: ^1.0.6   #控制横竖屏控件
  gzx_dropdown_menu: ^2.0.0+2
  better_player: ^0.0.33
  wakelock: ^0.2.0+1
  inview_notifier_list: ^1.0.0
  awsome_video_player: ^1.0.8+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # 屏幕适配
#  flutter_screenutil: ^0.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/ic_home_normal.png
    - images/ic_home_selected.png
    - images/ic_discovery_normal.png
    - images/ic_discovery_selected.png
    - images/ic_hot_normal.png
    - images/ic_hot_selected.png
    - images/ic_mine_normal.png
    - images/ic_mine_selected.png
    - images/icon_share.png
    - images/icon_arrow_right.png
    - images/icon_comment.png
    - images/icon_like.png
    - images/icon_share_white.png
    - images/icon_avatar.png
    - images/icon_like_grey.png
    - images/icon_comment_grey.png
    - images/icon_no_data.png
    - images/icon_default_avatar.png
    - images/icon_share_grey.png
    - images/bg_title.png
    - images/bg_splash.png
    - images/avatar.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
